# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignDesign_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignDesign_Example
  pod 'MBProgressHUD', '~> 1.0.0'

end
